name: Deploy Pipeline
on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "amondnet/vercel-action@v20"
        with:
          vercel-token: "${{ secrets.VERCEL_TOKEN }}"
          vercel-org-id: "${{ secrets.ORG_ID }}"
          vercel-project-id: "${{ secrets.PROJECT_ID }}"
          vercel-args: "--env ENVIRONMENT=development"

  deploy-staging:
    needs: deploy-dev
    runs-on: "ubuntu-latest"
    environment:
      name: "staging"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "amondnet/vercel-action@v20"
        with:
          vercel-token: "${{ secrets.VERCEL_TOKEN }}"
          vercel-org-id: "${{ secrets.ORG_ID }}"
          vercel-project-id: "${{ secrets.PROJECT_ID }}"
          vercel-args: "--env ENVIRONMENT=staging"

  deploy-production:
    needs: deploy-staging
    runs-on: "ubuntu-latest"
    environment:
      name: "production"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "amondnet/vercel-action@v20"
        with:
          vercel-token: "${{ secrets.VERCEL_TOKEN }}"
          vercel-org-id: "${{ secrets.ORG_ID }}"
          vercel-project-id: "${{ secrets.PROJECT_ID }}"
          vercel-args: "--prod --env ENVIRONMENT=production"
