name: Vercel Pipeline
on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Link to Vercel Project
        run: |
          echo "Debug: Linking project"
          vercel link --token ${{ secrets.VERCEL_TOKEN }} --yes
      - name: Deploy to Development
        run: |
          echo "Debug: Starting development deployment"
          vercel --token ${{ secrets.VERCEL_TOKEN }} --confirm

  deploy-production:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Link to Vercel Project
        run: |
          vercel link --token ${{ secrets.VERCEL_TOKEN }} --yes
      - name: Deploy to Production
        run: |
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
